name: Tagging

on:
  workflow_run:
    workflows: ['Version']
    types:
      - completed

jobs:
  version:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tagging
        run: |
          tag=$(cat package.json | grep '"version"' | awk -F '"' '{print $4}')
          tag=$tag_${{ github.head_ref }}
          git tag $tag
          git push origin $tag
