name: Tagging

on:
  push:
    branches: ['main', 'dev']

jobs:
  version:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Version
        run: |
          npm version patch
          git push origin ${{ github.base_ref }}

      - name: Tagging
        run: |
          tag=$(cat package.json | grep '"version"' | awk -F '"' '{print $4}')
          tag=${{ github.base_ref }}-$tag
          git tag $tag
          git push origin $tag
